project_id: 462614
api_token_env: CROWDIN_API_TOKEN
base_path: .
base_url: https://api.crowdin.com

preserve_hierarchy: false

files:
  - source: /src/i18n/lang/*.json
    #
    # Where translations will be placed
    # e.g. "/resources/%two_letters_code%/%original_file_name%"
    #
    translation: /src/i18n/lang/%two_letters_code%/%original_file_name%
    #
    # files or directories for ignore
    # e.g. ["/**/?.txt", "/**/[0-9].txt", "/**/*\?*.txt"]
    #
    #"ignore" : [],
    #
    # The dest allows you to specify a file name in Crowdin
    # e.g. "/messages.json"
    #
    #"dest" : "",
